/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import models.Carnivore;
import models.Herbivore;
import utils.Pair;

import java.util.ArrayList;

/**
 *
 * @author Suthasoma
 */
public class Baca extends javax.swing.JFrame {

    private ArrayList<CardItem> field = new ArrayList<>();
    /**
     * Creates new form Baca
     */
    public Baca() {
        initComponents();
//        for (int i = 0; i < 20; i++) {
////            this.jPanel1.add(new CardItem(new Carnivore(), null, CardItem.FIELD_CARD, new Pair<>(1,1), this, true));
//            field.add(new CardItem(new Carnivore(), null, CardItem.FIELD_CARD, new Pair<>(1,1), this, true));
//        }
//
//
//        for (int i = 0; i < 20; i++) {
//            this.jPanel1.add(field.get(i));
//        }
//
//        for (int i = 0; i < 6; i++) {
//            this.field.get(i).setCardItem(new Herbivore("SAPI"), null, CardItem.FIELD_CARD, new Pair<>(1,1), this, true);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardItem1 = new gui.CardItem(new Carnivore(), null, CardItem.FIELD_CARD, new Pair<Integer, Integer>(0, 0), this, true);
        cardItem2 = new gui.CardItem(new Carnivore(), null, CardItem.FIELD_CARD, new Pair<Integer, Integer>(0, 0), this, true);
        cardItem3 = new gui.CardItem();
        cardItem4 = new gui.CardItem();
        cardItem5 = new gui.CardItem();
        cardItem6 = new gui.CardItem();
        cardItem7 = new gui.CardItem();
        cardItem8 = new gui.CardItem();
        cardItem9 = new gui.CardItem();
        cardItem10 = new gui.CardItem();
        cardItem11 = new gui.CardItem();
        cardItem12 = new gui.CardItem();
        cardItem13 = new gui.CardItem();
        cardItem14 = new gui.CardItem();
        cardItem15 = new gui.CardItem();
        cardItem16 = new gui.CardItem();
        cardItem17 = new gui.CardItem();
        cardItem18 = new gui.CardItem();
        cardItem19 = new gui.CardItem();
        cardItem20 = new gui.CardItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);
        jPanel1.add(cardItem1);
        jPanel1.add(cardItem2);
        jPanel1.add(cardItem3);
        jPanel1.add(cardItem4);
        jPanel1.add(cardItem5);
        jPanel1.add(cardItem6);
        jPanel1.add(cardItem7);
        jPanel1.add(cardItem8);
        jPanel1.add(cardItem9);
        jPanel1.add(cardItem10);
        jPanel1.add(cardItem11);
        jPanel1.add(cardItem12);
        jPanel1.add(cardItem13);
        jPanel1.add(cardItem14);
        jPanel1.add(cardItem15);
        jPanel1.add(cardItem16);
        jPanel1.add(cardItem17);
        jPanel1.add(cardItem18);
        jPanel1.add(cardItem19);
        jPanel1.add(cardItem20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.CardItem cardItem1;
    private gui.CardItem cardItem10;
    private gui.CardItem cardItem11;
    private gui.CardItem cardItem12;
    private gui.CardItem cardItem13;
    private gui.CardItem cardItem14;
    private gui.CardItem cardItem15;
    private gui.CardItem cardItem16;
    private gui.CardItem cardItem17;
    private gui.CardItem cardItem18;
    private gui.CardItem cardItem19;
    private gui.CardItem cardItem2;
    private gui.CardItem cardItem20;
    private gui.CardItem cardItem3;
    private gui.CardItem cardItem4;
    private gui.CardItem cardItem5;
    private gui.CardItem cardItem6;
    private gui.CardItem cardItem7;
    private gui.CardItem cardItem8;
    private gui.CardItem cardItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
