/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;


import models.*;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.TransferHandler;
/**
 *
 * @author Suthasoma
 */
public class CardItem extends JPanel {

    /**
     * Creates new form FieldItem
     */
    public CardItem() {
        initComponents();
        initPreferredSize();
        setObject(new Herbivore("SAPI"));
        object.setActive(false);
        refreshData();
        addDragListener();
        setTransferHandler(new TransferGameHandler());
    }

    public CardItem(GameObject object) {
        initComponents();
        initPreferredSize();
        setObject(object);
        refreshData();
        addDragListener();
        setTransferHandler(new TransferGameHandler());
    }

    public GameObject getObject() {
        return object;
    }

    public void setObject(GameObject object) {
        this.object = object;
        this.object.setParent(this);
        refreshData();
    }

    public void removeObject() {
        setObject(new Herbivore("SAPI"));
        this.object.setActive(false);
        refreshData();
    }

    public void initPreferredSize() {
        this.setSize(new Dimension(252, 368));
        this.setMinimumSize(new Dimension(200, 320));
        imageLabel.setSize(new Dimension(251, 350));
    }

    public void refreshData() {
        if (object == null || !object.isActive()) {
            imageLabel.setIcon(new ImageIcon(icons.Icon.NOTHING.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH)));
            nameLabel.setText(" ");
            return;
        }
        imageLabel.setIcon(new ImageIcon(object.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH)));
        nameLabel.setText(object.getName());
    }

    public void addDragListener() {
//        putClientProperty("transfer.data", object);
        addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                CardItem parent = (CardItem) e.getSource();
                parent.putClientProperty("transfer.data", parent.getObject());
                TransferHandler handler = parent.getTransferHandler();
                handler.exportAsDrag(parent, e, TransferHandler.MOVE);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();

        nameLabel.setText("jLabel2");
        jPanel1.add(nameLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private GameObject object;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
