/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import models.GameObject;
import javax.swing.JPanel;
import models.Carnivore;

/**
 *
 * @author Suthasoma
 */
public class CardShuffle extends JPanel {

    private GameObject object;
    private boolean picked = false;
    /**
     * Creates new form CardShuffle
     */
    public CardShuffle() {
        this(new Carnivore());
    }
    
    public CardShuffle(GameObject object) {
        this.object = object;
        initComponents();
        initPreferredSize();
        refreshCard();
    }
    
    public void initPreferredSize() {
        this.setSize(new Dimension(145, 175));
        this.setPreferredSize(new Dimension(145,185));
        this.setMinimumSize(new Dimension(145, 185));
        this.setMaximumSize(new Dimension(145, 185));
        imageLabel.setSize(new Dimension(145, 133));
        imageLabel.setPreferredSize(new Dimension(145,133));
        imageLabel.setMaximumSize(new Dimension(145, 133));
    }
    
    public void swapShuffleColor() {
        if (!isPicked()) {
            roundedPane1.setBackground(new Color(0.392f, 0.2f, 0.0431f, 0.78f));
            picked = true;
        } else {
            roundedPane1.setBackground(new Color(0.392f, 0.2f, 0.0431f, 0.97f));
            picked = false;
        }
    }
    
    public boolean isPicked() {
        return picked;
    }
    
    public GameObject getObject() {
        return object;
    }
    
    public void setObject(GameObject object) {
        this.object = object;
        refreshCard();
    }
    
    public void refreshCard() {
        imageLabel.setIcon(new ImageIcon(object.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), java.awt.Image.SCALE_SMOOTH)));
        nameLabel.setText(object.getNameParsed());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPane1 = new gui.RoundedPane();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(145, 160));
        setLayout(new java.awt.BorderLayout());

        roundedPane1.setBackground(new Color(0.392f, 0.2f, 0.0431f, 0.97f));
        roundedPane1.setRoundBottomLeft(25);
        roundedPane1.setRoundBottomRight(25);
        roundedPane1.setRoundTopLeft(25);
        roundedPane1.setRoundTopRight(25);

        jPanel1.setOpaque(false);

        nameLabel.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("jLabel2");
        jPanel1.add(nameLabel);

        imageLabel.setPreferredSize(new java.awt.Dimension(145, 133));
        imageLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imageLabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout roundedPane1Layout = new javax.swing.GroupLayout(roundedPane1);
        roundedPane1.setLayout(roundedPane1Layout);
        roundedPane1Layout.setHorizontalGroup(
            roundedPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        roundedPane1Layout.setVerticalGroup(
            roundedPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPane1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(roundedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void imageLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imageLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_imageLabelAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private gui.RoundedPane roundedPane1;
    // End of variables declaration//GEN-END:variables
}
